# Generated by Django 6.0.2 on 2026-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
