# Generated by Django 6.0.1 on 2026-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dept_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dept_budget',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='dept_code',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='dept_desc',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='dept_emp',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='dept_head',
        ),
    ]
