# Generated by Django 6.0.1 on 2026-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emp_rename_dept_budget_dept_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_password',
            field=models.CharField(default=12345, max_length=20),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_contact',
            field=models.IntegerField(),
        ),
    ]
