# Generated by Django 6.0.1 on 2026-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emp_emp_password_alter_emp_emp_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Query', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('admin_rep', models.CharField(blank=True)),
            ],
        ),
    ]
