# Generated by Django 6.0.1 on 2026-02-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dept'),
        ),
    ]
