# Generated by Django 6.0.1 on 2026-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emp_emp_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='admin_rep',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
